# YAML = yaml aint a markup language
stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
    params:
    - data_ingestion.test_size

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    outs:
    - data/features
    params:
    - feature_engineering.max_features

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/features
    - src/model_building.py
    outs:
    - model.pkl
    params:
    - model_building.n_estimators
    - model_building.learning_rate

  evaluation:
    cmd: python src/evaluation.py
    deps:
    - model.pkl
    - src/evaluation.py
    metrics:
    - metrics.json
